### ISSUE TITLE
Use `Schema#limits`

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-enter#38]
We are adding `Schema#limits` set https://github.com/ckeditor/ckeditor5-engine/issues/818. Enter feature should use that to not break `limit` elements.

I am wondering what should be a desired behavior in such situations. Instead of splitting the block should we insert a line-break as in nested editables in v4?

This resolves also point 2 in https://github.com/ckeditor/ckeditor5-enter/issues/3.

**Comment by scofalik** [comment]
I don't think we should add `<br>` anywhere ever.

Either nothing should happen or caret should be placed in next block element or new paragraph should be created after limit block. Something in those lines. We've discussed it when talking about blockqoute feature: https://github.com/ckeditor/ckeditor5/issues/393

**Comment by fredck** [comment]
Agree. As for the first implementation, it should probably do nothing.

We should be able to bring the soft-line-break later if it would ever make sense.

**Comment by Reinmar** [comment]
> Agree. As for the first implementation, it should probably do nothing.

Agree. The soft break model is tricky and not worth any work right now.

PS. It's a funny to recall that in CKE4 I had to implement a similar mechanism at some point. If enter mode P wasn't available, we were switching to enter mode BR. Soon after I realised that many times the expected result was enter mode none. It was beyond our reach in CKE4, so it's funny that it's the default behaviour in CKE5 :).

**Comment by scofalik** [comment]
What about escaping limit block when it is the last block in the content? Will `quote` be limit?
```html
<p>Lorem ipsum.</p>
<quote>
  <p>Let me out!!!</p>
  <p>[]</p>
</quote>
```

**Comment by Reinmar** [comment]
In this case `<quote>` won't be a limit. If you press enter twice in a middle of it it should be broken, which means that it's a different category of element.

And as for the implementation – this is the same story as with lists. A special behaviour of the quote feature. I wouldn't try to "hoist" it to the enter because we'd need to figure out how all this needs to be configured (through the schema) :D.
